version: '3.2'
services:
  plugin:
    image: ghcr.io/sandrobonazzola/arcaflow-plugin-lmsensor
    build: .
    volumes:
      - source: ./lmsensor.yaml
        target: /lmsensor.yaml
        type: bind
